const SET_PRODUTO_LISTA_COMPRA = "SET_PRODUTO_LISTA_COMPRA"
const REMOVE_PRODUTO_LISTA_COMPRA = "REMOVE_PRODUTO_LISTA_COMPRA"
const SET_VALOR_TOTAL = "SET_VALOR_TOTAL"
export default {
    SET_PRODUTO_LISTA_COMPRA,
    REMOVE_PRODUTO_LISTA_COMPRA,
    SET_VALOR_TOTAL
}